### PR TITLE
Removed enable command

### PR DESCRIPTION
**Pull request by satish153**
Removed enable command as it is not applicable to all the targets.

### CODE REVIEW

**Comment by satish153** [comment]
jenkins: testsuite= t2bit_disable;gcc_disable;ut_disable;bfrt_examples_disable;switch_14_disable;switch_hitless_disable;tof2_disable;tof3_disable;diag_disable;internal_p4_16_disable;p4_14_disable;p4rt_disable;tna_preset_disable; warm_init_disable; switch_16_disable

**Comment by qobilidop** [comment]
I have some questions about this change. Does it mean we could simply skip the `.enable()` calls when using TDI? Or are there other things we should do instead of `.enable()`?

For example, currently https://github.com/p4lang/p4-dpdk-target README suggests doing:

```
bfshell> tdi_python

tdi.<P4 program>.enable()
pipe = tdi.<P4 program>.pipe.ingress
from netaddr import IPAddress
pipe.<P4 table>.<P4 action>(<action parameters>)
eg) pipe.ipv4_lpm.add_with_send(dst_addr=IPAddress('192.168.2.0'),dst_addr_p_length=24, port=1)
```

After this change, I guess we can just do:

```
bfshell> tdi_python

pipe = tdi.<P4 program>.pipe.ingress
from netaddr import IPAddress
pipe.<P4 table>.<P4 action>(<action parameters>)
eg) pipe.ipv4_lpm.add_with_send(dst_addr=IPAddress('192.168.2.0'),dst_addr_p_length=24, port=1)
```

Is this correct?

**Comment by satish153** [comment]
This PR is to remove the 'enable' command from the common code. The choice to support this command is left to the targets.
I see that dpdk target is pointing to tdi older than this commit. So you need to use the 'enable' command.

**Comment by qobilidop** [comment]
That clarified my understanding. Thanks @satish153!

**Pull request merged**
